compile:
  scripts/compile-devnet.sh

deploy:
  scripts/deploy-devnet.sh
  
start:
  scripts/deploy-devnet.sh
  scripts/start-devnet.sh

stop:
  scripts/stop-devnet.sh

watch:
  scripts/watch-devnet.sh