#!/usr/bin/env bash
# Auto-generated by mosaik TDX builder — launch {{CRATE_NAME}} as a TDX guest VM.
#
# Usage: sudo ./launch-tdx.sh
#
# All file paths default to the same directory as this script.
# Override with environment variables if needed.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

OVMF="${OVMF:-$SCRIPT_DIR/{{CRATE_NAME}}-OVMF.fd}"
if [ ! -f "$OVMF" ]; then
    OVMF="/usr/share/ovmf/OVMF.fd"
fi
KERNEL="${KERNEL:-$SCRIPT_DIR/{{CRATE_NAME}}-vmlinuz}"
INITRD="${INITRD:-$SCRIPT_DIR/{{CRATE_NAME}}-initramfs.cpio.gz}"
MEMORY="${MEMORY:-{{MEMORY}}}"
CPUS="${CPUS:-{{CPUS}}}"
SSH_PORT="${SSH_PORT:-10022}"

for f in "$OVMF" "$KERNEL" "$INITRD"; do
    if [ ! -f "$f" ]; then
        echo "ERROR: File not found: $f" >&2
        echo "       (set the corresponding env var to override)" >&2
        exit 1
    fi
done

TDX_OBJECT='{"qom-type":"tdx-guest","id":"tdx0","sept-ve-disable":true,"quote-generation-socket":{"type":"vsock","cid":"2","port":"4050"}}'
CMDLINE="console=ttyS0 ip=dhcp"

echo "=== Launching TDX Guest ==="
echo "  OVMF:     $OVMF"
echo "  Kernel:   $KERNEL"
echo "  Initrd:   $INITRD"
echo "  Memory:   $MEMORY"
echo "  CPUs:     $CPUS"
echo "  SSH:      localhost:$SSH_PORT"
echo ""

exec qemu-system-x86_64 \
    -accel kvm \
    -cpu host,pmu=off \
    -smp "$CPUS" \
    -m "$MEMORY" \
    \
    -object "$TDX_OBJECT" \
    -machine q35,kernel-irqchip=split,confidential-guest-support=tdx0 \
    \
    -bios "$OVMF" \
    -kernel "$KERNEL" \
    -initrd "$INITRD" \
    -append "$CMDLINE" \
    \
    -netdev user,id=net0,{{SSH_FWD}} \
    -device virtio-net-pci,netdev=net0 \
    -device vhost-vsock-pci,guest-cid=3 \
    \
    -nographic \
    -nodefaults \
    -serial mon:stdio
