#!/usr/bin/env bash
# Self-extracting TDX guest launcher for {{CRATE_NAME}}
# Generated by mosaik TDX builder — contains vmlinuz + initramfs + OVMF.fd
#
# Usage:
#   sudo ./{{CRATE_NAME}}-run-qemu.sh
#
# Environment variables:
#   MEMORY    — guest RAM (default: {{MEMORY}})
#   CPUS      — guest vCPUs (default: {{CPUS}})
#   SSH_PORT  — host port forwarded to guest :22 (default: 10022)
#   OVMF      — override OVMF.fd path
#   KERNEL    — override vmlinuz path
#   INITRD    — override initramfs path
#   KEEP      — set to 1 to keep extracted files after exit

set -euo pipefail

MARKER="__PAYLOAD_BELOW__"
MEMORY="${MEMORY:-{{MEMORY}}}"
CPUS="${CPUS:-{{CPUS}}}"
SSH_PORT="${SSH_PORT:-10022}"

WORK_DIR=$(mktemp -d /tmp/{{CRATE_NAME}}-tdx.XXXXXX)
cleanup() {
    if [ "${KEEP:-0}" = "1" ]; then
        echo "Extracted files kept at: $WORK_DIR"
    else
        rm -rf "$WORK_DIR"
    fi
}
trap cleanup EXIT

echo "Extracting TDX guest image..."
PAYLOAD_LINE=$(grep -an "^$MARKER" "$0" | tail -1 | cut -d: -f1)
PAYLOAD_START=$((PAYLOAD_LINE + 1))
tail -n +$PAYLOAD_START "$0" | tar xzf - -C "$WORK_DIR"

OVMF="${OVMF:-$WORK_DIR/OVMF.fd}"
KERNEL="${KERNEL:-$WORK_DIR/vmlinuz}"
INITRD="${INITRD:-$WORK_DIR/initramfs.cpio.gz}"

if [ ! -f "$OVMF" ]; then
    OVMF="/usr/share/ovmf/OVMF.fd"
fi

for f in "$OVMF" "$KERNEL" "$INITRD"; do
    if [ ! -f "$f" ]; then
        echo "ERROR: Missing file: $f" >&2
        exit 1
    fi
done

TDX_OBJECT='{"qom-type":"tdx-guest","id":"tdx0","sept-ve-disable":true,"quote-generation-socket":{"type":"vsock","cid":"2","port":"4050"}}'
CMDLINE="console=ttyS0 ip=dhcp"

echo "=== Launching TDX Guest: {{CRATE_NAME}} ==="
echo "  OVMF:     $OVMF"
echo "  Kernel:   $KERNEL"
echo "  Initrd:   $INITRD"
echo "  Memory:   $MEMORY"
echo "  CPUs:     $CPUS"
echo "  SSH:      localhost:$SSH_PORT"
echo ""

exec qemu-system-x86_64 \
    -accel kvm \
    -cpu host,pmu=off \
    -smp "$CPUS" \
    -m "$MEMORY" \
    \
    -object "$TDX_OBJECT" \
    -machine q35,kernel-irqchip=split,confidential-guest-support=tdx0 \
    \
    -bios "$OVMF" \
    -kernel "$KERNEL" \
    -initrd "$INITRD" \
    -append "$CMDLINE" \
    \
    -netdev user,id=net0,{{SSH_FWD}} \
    -device virtio-net-pci,netdev=net0 \
    -device vhost-vsock-pci,guest-cid=3 \
    \
    -nographic \
    -nodefaults \
    -serial mon:stdio

__PAYLOAD_BELOW__
